### ISSUE TITLE
error in script re bind shape files into df

### ISSUE THREAD

**Issue by HedvigS** [skalyan91/south-up#1]
I'm having trouble with
```

> EEZ_shp_df <- EEZ_shp_simple %>% 
  bind(maptools::nowrapRecenter(EEZ_shp_simple)) %>% 
  aggregate(list(rep.int(EEZ_shp_simple$GEONAME,2)), FUN = identity) %>% 
  broom::tidy()

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'y' in selecting a method for function 'bind': error in evaluating the argument 'obj' in selecting a method for function 'recenter': package polyclip required for .nowrapPolygons

```

I suspect the problem lies in what package bind is meant to be from

**Comment by skalyan91** [comment]
The problem goes away if you load the `rgeos` package (though I have no idea why).

However! A bunch of other issues seem to have crept in while I wasn’t looking (because of updates to various packages)—issues that I was blissfully unaware of until just now, after I made the fateful decision to clear my RStudio environment :).

I think I’ll leave this issue open until I sort out these other things (and make a proper commit).

**Comment by HedvigS** [comment]
okay :)!

**Comment by skalyan91** [comment]
Whew! Fixed all the other issues (the shading on the shaded map was broken). See commit https://github.com/skalyan91/south-up/commit/aa12118e4058d64d587f913d4768a9a7eae691ef.

I also removed both `rgdal` and `rgeos` as dependencies (both of these packages will be discontinued later this year). Unfortunately, `maptools::nowrapRecenter()` still pulls in `rgeos`, and doesn’t work if I use the `avoidGEOS` option. The code _will_ break from October onwards—consider yourself warned!

**Comment by HedvigS** [comment]
hurray! many thanks!

**Comment by HedvigS** [comment]
maybe when that breaks, it could be switched to the old way you and i used to do it with LITERALLY manipulating the longitudes?

**Comment by HedvigS** [comment]
Btw I changed my mind about the national borders in EEZ, but I can clearly see what arguments to swap around to get them so all good. I just realised it's good to also have a version with those boundaries. I'm sorry for the trouble and thank you for your patience!

**Comment by skalyan91** [comment]
> maybe when that breaks, it could be switched to the old way you and i used to do it with LITERALLY manipulating the longitudes?

The challenge is how to do it with a `SpatialPolygons` object, rather than a data frame :).

**Comment by skalyan91** [comment]
> Btw I changed my mind about the national borders in EEZ, but I can clearly see what arguments to swap around to get them so all good. I just realised it's good to also have a version with those boundaries. I'm sorry for the trouble and thank you for your patience!

Happy to help! This is a project that I’m reasonably proud of, so it was fun to revisit it :).

**Comment by HedvigS** [comment]
> > maybe when that breaks, it could be switched to the old way you and i used to do it with LITERALLY manipulating the longitudes?
> 
> The challenge is how to do it with a `SpatialPolygons` object, rather than a data frame :).

new idea, how about using groundhog::groundhog.library() to install an older version of the pkg?

**Comment by skalyan91** [comment]
Genius! I’ll try that.

**Comment by skalyan91** [comment]
Yay, it works (see https://github.com/skalyan91/south-up/commit/54b6607be7a345db29a033b103b2cffe30839390)! My code is now preserved in amber for all eternity :). You’ll still get a bunch of warnings, though—but you can safely ignore those.

**Comment by HedvigS** [comment]
:D!
