### ISSUE TITLE
save rdata objects

### ISSUE THREAD

**Issue by HedvigS** [skalyan91/south-up#3]
i did some changes such that the map.R script saves rdata object, that I can use elsewhere :D 👯 
What do you think?

I also removed the non-boarders for eez, I realised i couldn't figure out a good use-case. sorry :(

I can't make PRs, so here's the branch: https://github.com/HedvigS/south-up

**Comment by skalyan91** [comment]
Added you as a collaborator; feel free to make a PR :).

**Comment by skalyan91** [comment]
Merged (https://github.com/skalyan91/south-up/commit/64a73531dde300990f58d63bd8082708699862a2)!
