### ISSUE TITLE
Have shading match orientation

### ISSUE THREAD

**Issue by skalyan91** [skalyan91/south-up#7]
@HedvigS I notice you’ve added an option that controls whether south is up or down. The thing is, the shading currently assumes that south is up (and the light source is in the south-east). If you want to produce a south-down map, then the shading should be such that the light source is in the north-west.

Want to try fixing this? Or if it isn’t the sort of thing that bothers you, then I’ll do it.

**Comment by HedvigS** [comment]
yes I mainly focussed on the flat one because it seemed easier.

The shading direction wasn't something I had thought about, feel free to roll that into the options

**Comment by skalyan91** [comment]
Fixed in https://github.com/skalyan91/south-up/commit/90da92d4d10701b105e2770dbd4dd921bae2eb37 (though the `.qs` files may have to be sliced into smaller chunks).
