### ISSUE TITLE
SH_misc package?

### ISSUE THREAD

**Issue by HedvigS** [skalyan91/south-up#8]
@skalyan91 would you want to have an r-package on cran with me called something like "SH_misc" (Siva Hedvig miscellaneous functions)?

There are several things you and I do in a similar way, and it'd be good to have a package on CRAN for some of it.

I'd be comfortable with something that's just misc.

suggestion for inclusions:

* south-up mapping with EEZ
* CLarbor
* some of the things over at my personal cookbook repos

**Comment by skalyan91** [comment]
I love the idea! But I’m not sure if CRAN would allow a package that doesn’t have a single, coherent purpose.

Another option would be to have a package on GitHub that can be installed with `devtools::install_github()`. Maybe it would be good to start with this approach in any case?

**Comment by skalyan91** [comment]
Also, is this a reference to [Hmisc](https://cran.r-project.org/web/packages/Hmisc/index.html) ;)? In fact, that is the closest parallel I can think of to what you’re proposing.

**Comment by HedvigS** [comment]
yeah i've seen different something_misc packages.

Let's look at CRAN guidelines.

**Comment by HedvigS** [comment]
I can see

"A package’s contribution has to be non-trivial."

**Comment by skalyan91** [comment]
Yes, I saw that. Also, “publication-quality”.

**Comment by HedvigS** [comment]
well, let's maybe start with a github thing and then see if we wanna go to cran later. Sound okay?

**Comment by skalyan91** [comment]
Yes! We can also decide later if we want to split our package into more focused packages that are better candidates for CRAN submission.

**Comment by HedvigS** [comment]
Yup!

Once #7 is solved, maybe we can move to merging south_up and CLarbor as a start?

**Comment by skalyan91** [comment]
https://github.com/skalyan91/south-up/issues/7 is now closed.
